=== Crowley2012/SubaruTuning/Definitions/Backup/cars_def.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dyno ( car+ ) >

<!ELEMENT car (type,carmass,finalratio,rollcoeff,dragcoeff,frontalarea,transmission,gearratio1,gearratio2,gearratio3,gearratio4,gearratio5?,gearratio6?,tirewidth,tireaspect,wheelsize) >
<!ELEMENT type (#PCDATA) >
<!ELEMENT carmass (#PCDATA) >
<!ELEMENT finalratio (#PCDATA) >
<!ELEMENT rollcoeff (#PCDATA) >
<!ELEMENT dragcoeff (#PCDATA) >
<!ELEMENT frontalarea (#PCDATA) >
<!ELEMENT transmission (#PCDATA) >
<!ELEMENT gearratio1 (#PCDATA) >
<!ELEMENT gearratio2 (#PCDATA) >
<!ELEMENT gearratio3 (#PCDATA) >
<!ELEMENT gearratio4 (#PCDATA) >
<!ELEMENT gearratio5 (#PCDATA) >
<!ELEMENT gearratio6 (#PCDATA)  >
<!ELEMENT tirewidth (#PCDATA) >
<!ELEMENT tireaspect (#PCDATA) >
<!ELEMENT wheelsize (#PCDATA) >

=== Crowley2012/SubaruTuning/Definitions/Backup/cars_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dyno SYSTEM "cars_def.dtd">
<!-- All tags must be included and in specified order when adding
	 a new car definition, the exception is gearratio# where only
	 applicable gears are to be listed.	 Car Type tags containing
	 an * denotes this is not the OEM configuration for the vehicle,
	 but rather a custom user defined configuration.
	 
	 Version 14: 2011-11-03
-->
<dyno>
	<car>
		<type>01 JDM WRX STi 6MT</type>
		<carmass>3295</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>1.061</gearratio5>
		<gearratio6>0.842</gearratio6>
		<tirewidth>225</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>02 ADM WRX STi 6MT</type>
		<carmass>3153</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>1.061</gearratio5>
		<gearratio6>0.842</gearratio6>
		<tirewidth>225</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>02 E/USDM WRX 4AT</type>
		<carmass>3140</carmass>
		<finalratio>4.111</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>automatic</transmission>
		<gearratio1>2.785</gearratio1>
		<gearratio2>1.545</gearratio2>
		<gearratio3>1</gearratio3>
		<gearratio4>0.694</gearratio4>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>02 E/USDM WRX 5MT</type>
		<carmass>3085</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.454</gearratio1>
		<gearratio2>1.947</gearratio2>
		<gearratio3>1.366</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>02 E/USDM WRX WGN 4AT</type>
		<carmass>3220</carmass>
		<finalratio>4.111</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>automatic</transmission>
		<gearratio1>2.785</gearratio1>
		<gearratio2>1.545</gearratio2>
		<gearratio3>1</gearratio3>
		<gearratio4>0.694</gearratio4>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>02 E/USDM WRX WGN 5MT</type>
		<carmass>3165</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.454</gearratio1>
		<gearratio2>1.947</gearratio2>
		<gearratio3>1.366</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>02 EDM WRX STi 6MT</type>
		<carmass>3351</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>0.971</gearratio5>
		<gearratio6>0.756</gearratio6>
		<tirewidth>215</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>02 JDM WRX STi 6MT</type>
		<carmass>3295</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>1.061</gearratio5>
		<gearratio6>0.842</gearratio6>
		<tirewidth>225</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>03 E/JDM Legacy B4 2.0GT 5MT</type>
		<carmass>3109</carmass>
		<finalratio>4.111</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.28</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.166</gearratio1>
		<gearratio2>1.882</gearratio2>
		<gearratio3>1.296</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>215</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>03 E/USDM WRX 5MT</type>
		<carmass>3085</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.454</gearratio1>
		<gearratio2>1.947</gearratio2>
		<gearratio3>1.366</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>03 E/USDM WRX WGN 5MT</type>
		<carmass>3165</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.454</gearratio1>
		<gearratio2>1.947</gearratio2>
		<gearratio3>1.366</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>03 EDM WRX STi 6MT</type>
		<carmass>3351</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>0.971</gearratio5>
		<gearratio6>0.756</gearratio6>
		<tirewidth>215</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>03 JDM WRX STi 6MT</type>
		<carmass>3295</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>1.061</gearratio5>
		<gearratio6>0.842</gearratio6>
		<tirewidth>225</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>04 ADM WRX STi 6MT</type>
		<carmass>3240</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>1.061</gearratio5>
		<gearratio6>0.842</gearratio6>
		<tirewidth>225</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>04 E/USDM FXT 4AT</type>
		<carmass>3250</carmass>
		<finalratio>4.444</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>automatic</transmission>
		<gearratio1>2.785</gearratio1>
		<gearratio2>1.545</gearratio2>
		<gearratio3>1</gearratio3>
		<gearratio4>0.694</gearratio4>
		<tirewidth>215</tirewidth>
		<tireaspect>60</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>04 E/USDM FXT 5MT</type>
		<carmass>3150</carmass>
		<finalratio>4.444</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.454</gearratio1>
		<gearratio2>1.947</gearratio2>
		<gearratio3>1.366</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>215</tirewidth>
		<tireaspect>60</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>04 E/USDM WRX 5MT</type>
		<carmass>3085</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.454</gearratio1>
		<gearratio2>1.947</gearratio2>
		<gearratio3>1.366</gearratio3>
		<gearratio4>0.972</gearratio4>
		<gearratio5>0.738</gearratio5>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>04 E/USDM WRX STi 6MT</type>
		<carmass>3351</carmass>
		<finalratio>3.9</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>manual</transmission>
		<gearratio1>3.636</gearratio1>
		<gearratio2>2.375</gearratio2>
		<gearratio3>1.761</gearratio3>
		<gearratio4>1.346</gearratio4>
		<gearratio5>0.971</gearratio5>
		<gearratio6>0.756</gearratio6>
		<tirewidth>225</tirewidth>
		<tireaspect>45</tireaspect>
		<wheelsize>17</wheelsize>
	</car>
	<car>
		<type>04 E/USDM WRX WGN 4AT</type>
		<carmass>3220</carmass>
		<finalratio>4.111</finalratio>
		<rollcoeff>0.015</rollcoeff>
		<dragcoeff>0.33</dragcoeff>
		<frontalarea>22</frontalarea>
		<transmission>automatic</transmission>
		<gearratio1>2.785</gearratio1>
		<gearratio2>1.545</gearratio2>
		<gearratio3>1</gearratio3>
		<gearratio4>0.694</gearratio4>
		<tirewidth>205</tirewidth>
		<tireaspect>55</tireaspect>
		<wheelsize>16</wheelsize>
	</car>
	<car>
		<type>04 E/USDM WRX WGN 5MT</type>
		<carmass>3165</carmass>
		<finalratio>3.9</finalratio>
